# Generated by Django 3.2.8 on 2025-11-29 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20251128_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='member_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='member_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
